# Generated by Django 2.1.4 on 2018-12-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20181208_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='users', to='mainapp.Hobby'),
        ),
    ]
